# Generated by Django 4.2.5 on 2024-02-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_cart_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='razorpay_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
