# Generated by Django 4.2.5 on 2024-02-03 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_order_razorpay_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='razorpay_id',
            new_name='razorpay_payment_id',
        ),
    ]
