# Generated by Django 4.2.5 on 2024-02-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_rename_razorpay_id_order_razorpay_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='isdeliverd',
            field=models.BooleanField(default=False),
        ),
    ]
