# Generated by Django 4.2.5 on 2024-02-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_order_order_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
