# Generated by Django 4.2.5 on 2024-02-26 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_remove_order_id_alter_order_order_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='order_no',
            new_name='trackingcode',
        ),
    ]
