# Generated by Django 4.2.5 on 2024-02-27 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_rename_order_no_cart_trackingcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='order_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
